[package]
name = "terra-rust-script"
version = "0.1.0"
authors = ["CyberHoward"]
edition = "2018"

[workspace]

[dependencies]
cw2 = { version = "0.8" }
cw20 = { version = "0.8" }
cosmwasm-bignumber = "2.2"
cosmwasm-std = { version = "0.16" }
cosmwasm-storage = { version = "0.16" }
cw-storage-plus = { version = "0.8" }
cw-controllers = { version = "0.8" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
terra-cosmwasm = "2.2"
terraswap = "2.4.0"
thiserror = { version = "1.0.21" }
protobuf = { version = "2", features = ["with-bytes"] }
terra-rust-api = {version ="1.2"}
tokio = { version = "1.4", features = ["full"] }
secp256k1 = { version = "0.20.3", default-features = false }
log="0.4.14"
anyhow="1.0"
serde_json = "1.0.79"
reqwest = { version = "0.11.9"}
dotenv="0.15.0"
env_logger = "0.8.3"
base64 = "0.13.0"
async-trait = "0.1.53"